services:
    - type: web
      name: bookish-social-network
      env: node
      plan: free
      startCommand: node server/server.js
      buildCommand: webpack --mode production

databases:
    - name: socialnetwork
      plan: free
